namespace: zjpeterson
name: aci
version: 0.2.0
readme: README.md
authors:
  - Zach Peterson (@zjpeterson)
description: Ansible collection for use with Cisco ACI
license_file: LICENSE
tags:
  - cisco
  - aci
  - collection
  - inventory
  - networking
  - sdn
repository: https://github.com/zjpeterson/ansible-aci
issues: https://github.com/zjpeterson/ansible-aci/issues
documentation: https://github.com/zjpeterson/ansible-aci/tree/master/docs
