namespace: zjpeterson
name: aci
version: 0.2.1
readme: README.md
authors:
  - Zach Peterson (@zjpeterson)
description: Ansible collection for use with Cisco ACI, focused on the use of Ansible Tower
license_file: LICENSE
tags:
  - cisco
  - aci
  - collection
  - inventory
  - networking
  - sdn
repository: https://github.com/zjpeterson/ansible-tower-aci
issues: https://github.com/zjpeterson/ansible-tower-aci/issues
documentation: https://github.com/zjpeterson/ansible-tower-aci/tree/master/docs
