---
- name: Apply key to credential {{ tower_cred_name }}
  awx.awx.tower_credential:
    name: "{{ tower_cred_name }}"
    organization: "{{ tower_cred_org }}"
    credential_type: "{{ tower_cred_type }}"
    inputs:
      username: "{{ apic_user }}"
      private_key: "{{ lookup('file', role_path + '/' + apic_user + '.pem') }}"
